INSERT INTO Restaurant_Dimension (Restaurant_ID, Restaurant_Name, Cuisine_Type, Location, Rating)
VALUES
(1, 'Pizza Palace', 'Italian', 'New York', 4.5),
(2, 'Sushi World', 'Japanese', 'Los Angeles', 4.2),
(3, 'Burger Haven', 'American', 'Chicago', 4.7),
(4, 'Taco Fiesta', 'Mexican', 'San Francisco', 4.3),
(5, 'Curry House', 'Indian', 'Houston', 4.0),
(6, 'Pasta Paradise', 'Italian', 'Miami', 4.4),
(7, 'Ramen Republic', 'Japanese', 'Boston', 4.6),
(8, 'BBQ Joint', 'American', 'Dallas', 4.1),
(9, 'Dumpling Den', 'Chinese', 'Seattle', 4.3),
(10, 'Sandwich Shack', 'American', 'Denver', 4.2),
(11, 'Pasta Place', 'Italian', 'Austin', 4.5),
(12, 'Pho Paradise', 'Vietnamese', 'San Diego', 4.7),
(13, 'Steak House', 'American', 'Los Angeles', 4.8),
(14, 'Falafel Feast', 'Middle Eastern', 'Washington, D.C.', 4.3),
(15, 'Churro Corner', 'Spanish', 'New York', 4.4),
(16, 'Sushi Bar', 'Japanese', 'Portland', 4.2),
(17, 'Pizza Point', 'Italian', 'Miami', 4.1),
(18, 'BBQ Barn', 'American', 'Chicago', 4.3),
(19, 'Biryani Bites', 'Indian', 'Atlanta', 4.6),
(20, 'Taco Town', 'Mexican', 'San Antonio', 4.4),
(21, 'Wok This Way', 'Chinese', 'New York', 4.5),
(22, 'Grill Guys', 'American', 'Los Angeles', 4.7),
(23, 'Dim Sum Delight', 'Chinese', 'San Francisco', 4.0),
(24, 'Shawarma Shop', 'Middle Eastern', 'Houston', 4.2),
(25, 'Noodle House', 'Asian', 'Dallas', 4.4),
(26, 'Bagel Bliss', 'American', 'Chicago', 4.3),
(27, 'Wrap World', 'Mediterranean', 'Portland', 4.5),
(28, 'Kebab Kingdom', 'Middle Eastern', 'Boston', 4.6),
(29, 'Waffle Wonder', 'Belgian', 'Seattle', 4.4),
(30, 'Chili Champs', 'American', 'Denver', 4.3);
